### ISSUE TITLE
joomla 1.5 install

### ISSUE THREAD

**Issue by gaetgodi** [betweenbrain/Menu-Wrench#12]
This gives me an error message when trying to install in joomla 1.5, is there a special technique I should be using?
Error! Could not find a Joomla! XML setup file in the package.

**Comment by betweenbrain** [comment]
For Joomla 1.5, you will need to use the file at https://github.com/betweenbrain/Menu-Wrench/archive/1.5-master.zip

**Comment by gaetgodi** [comment]
Thank you very much, will try it tomorrow.
Gaetan

**Comment by betweenbrain** [comment]
You're welcome. Please let me know if you have any other issues.
