### ISSUE TITLE
How do you show only the child items and not the parent

### ISSUE THREAD

**Issue by 2babooblabla** [betweenbrain/Menu-Wrench#13]
How do you show only the child items and not the parent (the one you choose in Rendered Items)?
I thought I had already achieved this but can't figure out how anymore. Or is it not possible?

Example : I have
- Parent Link
  ---Child1
  ---Child2
  ---Child3
  I want to show only the children, not the parent.

Matt answered : "Thanks for the feedback. If it looks like it;s working well, I'll add this to the next release.

To render only child items, you would need to select them as the items to render, and not their parents"

**Comment by betweenbrain** [comment]
Thanks for posting this @2babooblabla. I'm going to close it as it is solved, but it will remain on GitHub for others to learn from.
