### ISSUE TITLE
Breaks main menu

### ISSUE THREAD

**Issue by 2babooblabla** [betweenbrain/Menu-Wrench#19]
Hello again Matt,

I'm coming back to you about wrench menu.
displays ok but my main menu, if you hover over level0 "the mag" is all messed up :  underconstructionsite:www"dot"terre-escales.com/2014/le-mag/sommaire"dot"html

My guess is that it comes from the special caracters used in the wrench menu items.

Please let me know if you know a way to solve this.

Maybe it depends on the way the module for my main menu works but my first guess is a conflict between those special characters and your modification for the image display.

thanks!!

Paul

**Comment by betweenbrain** [comment]
Hello Paul,

Are you using the latest version of Menu Wrench from https://github.com/betweenbrain/Menu-Wrench/releases? Also, have you tried disabling whatever is manipulating the menu for the mega display?

**Comment by 2babooblabla** [comment]
Hello,

Just installed the latest version but no difference.
The problem does not arrise in wrench menu. It arrises in the mega menu only on pages where wrench menu is activated and where wrench menu items have special characters like ê or '.

If i disable wrench menu on that page, top menu goes back to normal.

I inserted a link to site so you can it in my first post. The link is not clickable as I do not want a real link here for now. Just replace "dot" with . in the above link.

thanks for your help!

**Comment by betweenbrain** [comment]
> The problem does not arrise in wrench menu. It arrises in the mega menu only on pages where wrench menu is activated and where wrench menu items have special characters like ê or '.

Does this issue arise when you have special characters in non-menu wrench items and when using the mega menu?

The issue I see is that the markup becomes `<img src="/2014/images/blank-menu.jpg" alt="<img src=" 2014="" images="" blank-menu.jpg"="">` with the mega menu enabled.

Can you tell me where I can download this mega menu plugin?

**Comment by 2babooblabla** [comment]
The megamenu is not free.
So find it here attached (sent by email).
On all other pages all is fine. And in french you get those special characters often.

**Comment by 2babooblabla** [comment]
Meganu is not free.
So find it here attached (sent by email).
On all other pages all is fine. And in french you get those special 
characters often.

**Comment by betweenbrain** [comment]
Thanks. The email attachment will not get posted here. Can you email it directly to me at matt@betweenbrain.com

**Comment by 2babooblabla** [comment]
i already did some time ago
find attached again.
thanks

**Comment by betweenbrain** [comment]
> i already did some time ago
> find attached again.
> thanks

Please note that you are emailing Github, and not me directly, when your reply to these notifications.

**Comment by betweenbrain** [comment]
Please try the development version to see if this solves the issue - https://github.com/betweenbrain/Menu-Wrench/archive/develop.zip

Thanks!

**Comment by 2babooblabla** [comment]
Problem remains.

**Comment by betweenbrain** [comment]
If you don't mind, please try it again. I have made some additional changes.

**Comment by 2babooblabla** [comment]
works!!! many thanks!

**Comment by betweenbrain** [comment]
Excellent! You're very welcome!

I would appreciate it very much if you could take a couple of minutes and leave a review at http://extensions.joomla.org/extensions/structure-a-navigation/menu-systems/menu-editors/27376
