### ISSUE TITLE
Add Menu Class Suffix support

### ISSUE THREAD

**Issue by 01Kuzma** [betweenbrain/Menu-Wrench#22]
Hi!
Really need this feature in order to override the ul class=menu value

**Comment by betweenbrain** [comment]
Hello,

I agree that this is a very useful feature, and that I'll add as soon as I can. In the meantime, why don't you  create a template override to change it?

**Comment by 01Kuzma** [comment]
Hi! 
Thank you very much!
Just forget about template overrides :) 
That sounds as temporary solution for it :+1:

**Comment by betweenbrain** [comment]
Cheers! And, thanks for reminding me to add this feature. I seem to keep forgetting to do it.

I would appreciate it very much if you could take a couple of minutes and leave a review at http://extensions.joomla.org/extensions/structure-a-navigation/menu-systems/menu-editors/27376

Thanks!

**Comment by 01Kuzma** [comment]
No problem! 
Thank you for great extension :+1:

**Comment by 01Kuzma** [comment]
Hi!
I see that you have made some changed in the code.
I have updated module on localhost but can't find the input where I could paste the menu class suffix.
Could you guide me please?
Thank you!

**Comment by betweenbrain** [comment]
Hello,

This would be entered in the module manager when editing the module. It uses the standard module class suffix field.

Hope that helps!

**Comment by 01Kuzma** [comment]
Great, thank you!
