### ISSUE TITLE
menu wrench error on user registration

### ISSUE THREAD

**Issue by jguardia9** [betweenbrain/Menu-Wrench#24]
This module achieve plently my needs, but when I try to register an user to the web the screen apears white an notihng hapen. Activing the errors notification it appears the following one:

Notice: Undefined property: stdClass::$id in /htdocs/public/www/modules/mod_menuwrench/helper.php on line 101 Notice: Undefined property: stdClass::$id in /htdocs/public/www/modules/mod_menuwrench/helper.php on line 101 Notice: Undefined property: stdClass::$params in /htdocs/public/www/modules/mod_menuwrench/helper.php on line 107 Fatal error: Call to a member function get() on a non-object in /htdocs/public/www/modules/mod_menuwrench/helper.php on line 107

Thanks in advance

**Comment by jguardia9** [comment]
In adittion to my

**Comment by betweenbrain** [comment]
Sorry for the delay in responding. Did you resolve this issue?

**Comment by jguardia9** [comment]
Thank you for your answer

I have not resolved it, I am not an expert in code.

I could use this module to reduce the background effort in a multilingual
environment. If it do not work my by paas is do not use it and i will have
 a litle more work to implement the web.

I am working in a very standard hosting with the last version of joomla 3.

I could aptreciate if there is an easy solution

best regards

2015-02-26 15:52 GMT+01:00 Matt Thomas notifications@github.com:

> Sorry for the delay in responding. Did you resolve this issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/betweenbrain/Menu-Wrench/issues/24#issuecomment-76190849
> .

## 

Gracies i salutacions

_27S Neix un nou Estat_

Joan Guàrdia
jguardia9@gmail.com
93 812 23 16
609 322 347

**Comment by betweenbrain** [comment]
Hello,

I have been trying to reproduce this issue, but unfortunately I cannot. Can you provide as detailed as possible steps to reproduce? Are you using the core Joomla login module and core Joomla components for user registration? How are users configured in the back end?

**Comment by jguardia9** [comment]
Thank you for your interest.

I have done more test with the following results :

First of all I have updated joomla to joomla 3.4.0. Nothing changes. I
forget to inform you that i am using K2 in my web, but the k2 user
managements are disabled, I am using the joomla core login form. Despite of
this it is possible that k2 could afect to the error, because I have
experimented similar bad experience with k2 and some othe isusues.

I have installed again wrench, and I have test without login any user, it
works properly.

After this I have login with the admin user. The screen remains white and
if I active maximun errors level I coul see the same fatal error :

107 Fatal error: Call to a member function get() on a non-object in
/htdocs/public/www/modules/mod_menuwrench/helper.php on line 107

I have edited helper.php. I have elimnate 107 sentence if and get like this
:

/\* if ($item->params->get('menu_image', ''))
{
$item->menu_image = htmlspecialchars($item->params->get('menu_image', ''),
ENT_COMPAT, 'UTF-8', false);
} _/
using /_   */ and now it seams sto work porperly in both situations, with a
user register and without a user registred. Because I do not use images in
the menus I think I do not need this sentence ( Add image to item object if
one is defined in the menu item's parameters )

I would apreciate your opinion about if I could work with this by pass with
no problems.

Best regards

joan guardia

2015-02-27 20:21 GMT+01:00 Matt Thomas notifications@github.com:

> Hello,
> 
> I have been trying to reproduce this issue, but unfortunately I cannot.
> Can you provide as detailed as possible steps to reproduce? Are you using
> the core Joomla login module and core Joomla components for user
> registration? How are users configured in the back end?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/betweenbrain/Menu-Wrench/issues/24#issuecomment-76454871
> .

## 

Gracies i salutacions

_27S Neix un nou Estat_

Joan Guàrdia
jguardia9@gmail.com
93 812 23 16
609 322 347

**Comment by betweenbrain** [comment]
Hello,

Does the issue only occur when you log into `/administrator` and not the front end?

**Comment by jguardia9** [comment]
No , the back end works properly.

The issue occurs in the front end when I log with any registered user, the
administrator or other.

2015-03-02 15:19 GMT+01:00 Matt Thomas notifications@github.com:

> Hello,
> 
> Does the issue only occur when you log into /administrator and not the
> front end?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/betweenbrain/Menu-Wrench/issues/24#issuecomment-76718702
> .

## 

Gracies i salutacions

_27S Neix un nou Estat_

Joan Guàrdia
jguardia9@gmail.com
93 812 23 16
609 322 347

**Comment by jguardia9** [comment]
Dear Matt. more information.

I have tried in a joomla native, it works properly with and witout user log.

I have tried in a test environment with the joomla standard template Beez 3
 IT NOT WORK

I have uninstall the k2 environment, IT NOT WORK.

Tomarrow I will try more testings.

Best regards

2015-03-02 16:53 GMT+01:00 joan guardia i martinez jguardia9@gmail.com:

> No , the back end works properly.
> 
> The issue occurs in the front end when I log with any registered user, the
> administrator or other.
> 
> 2015-03-02 15:19 GMT+01:00 Matt Thomas notifications@github.com:
> 
> > Hello,
> > 
> > Does the issue only occur when you log into /administrator and not the
> > front end?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/betweenbrain/Menu-Wrench/issues/24#issuecomment-76718702
> > .
> 
> ## 
> 
> Gracies i salutacions
> 
> _27S Neix un nou Estat_
> 
> Joan Guàrdia
> jguardia9@gmail.com
> 93 812 23 16
> 609 322 347

## 

Gracies i salutacions

_27S Neix un nou Estat_

Joan Guàrdia
jguardia9@gmail.com
93 812 23 16
609 322 347

**Comment by jguardia9** [comment]
Dear Matt :

I have made a lot of test in a local environment and at the end i have
surrended.

I have uninstalled one by one all the added extensions in a copy of my web,
until arrive to a native joomla 3, and the problem persist.

In oposition I have tryed in a new native joomla 3 and it works perfectly.

It seems that there is some corrupted in the joomla 3 of my life web, but i
can not find waht it is, and i can not reinstall all starting from zero
because the production web is complex and near to be finished.

The only question, from my point of view, is to now if I could use your
extension excluding the sentece that produce the error, as I said in a
previous email-

Thanks in advance and best regards

2015-03-02 21:12 GMT+01:00 joan guardia i martinez jguardia9@gmail.com:

> Dear Matt. more information.
> 
> I have tried in a joomla native, it works properly with and witout user
> log.
> 
> I have tried in a test environment with the joomla standard template Beez
> 3  IT NOT WORK
> 
> I have uninstall the k2 environment, IT NOT WORK.
> 
> Tomarrow I will try more testings.
> 
> Best regards
> 
> 2015-03-02 16:53 GMT+01:00 joan guardia i martinez jguardia9@gmail.com:
> 
> > No , the back end works properly.
> > 
> > The issue occurs in the front end when I log with any registered user,
> > the administrator or other.
> > 
> > 2015-03-02 15:19 GMT+01:00 Matt Thomas notifications@github.com:
> > 
> > > Hello,
> > > 
> > > Does the issue only occur when you log into /administrator and not the
> > > front end?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/betweenbrain/Menu-Wrench/issues/24#issuecomment-76718702
> > > .
> > 
> > ## 
> > 
> > Gracies i salutacions
> > 
> > _27S Neix un nou Estat_
> > 
> > Joan Guàrdia
> > jguardia9@gmail.com
> > 93 812 23 16
> > 609 322 347
> 
> ## 
> 
> Gracies i salutacions
> 
> _27S Neix un nou Estat_
> 
> Joan Guàrdia
> jguardia9@gmail.com
> 93 812 23 16
> 609 322 347

## 

Gracies i salutacions

_27S Neix un nou Estat_

Joan Guàrdia
jguardia9@gmail.com
93 812 23 16
609 322 347

**Comment by betweenbrain** [comment]
Hello,

Apologies for the delay. Unfortunately, I have not been able to reproduce this issue. If there is any chance that you can create and upload backup of a test site, or allow me access to a site that exhibits this issue?

>  if I could use your extension excluding the sentence that produce the error

Yes, that may be fine. But, I'd prefer to try and resolve this issue at the root as commenting that line may have other unforeseen issues.

**Comment by jguardia9** [comment]
Thank you for your interest, Matt.

The truth is that I have discovered that the funcionality I need is
included in the core joomla. It was my mistake. sorry for it. Because this,
I have uninstalled menu-wrench.

As result of my diferent tests, I informed you in other emails, I have
arrived to the conclusion that there is something wrong in my joomla
installation, because I can not reproduce too the error in a joomla native.

In my opinion the topic could be closed.

Thanks for all and best regards.

2015-03-09 14:22 GMT+01:00 Matt Thomas notifications@github.com:

> Hello,
> 
> Apologies for the delay. Unfortunately, I have not been able to reproduce
> this issue. If there is any chance that you can create and upload backup of
> a test site, or allow me access to a site that exhibits this issue?
> 
> if I could use your extension excluding the sentence that produce the error
> 
> Yes, that may be fine. But, I'd prefer to try and resolve this issue at
> the root as commenting that line may have other unforeseen issues.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/betweenbrain/Menu-Wrench/issues/24#issuecomment-77851629
> .

## 

Gracies i salutacions

_27S Neix un nou Estat_

Joan Guàrdia
jguardia9@gmail.com
93 812 23 16
609 322 347

**Comment by betweenbrain** [comment]
That's great that you are able to solve your needs with core Joomla. That is always better.

Best of luck to you!
