### ISSUE TITLE
Menu assignment tab layout is broken

### ISSUE THREAD

**Issue by Delemo** [betweenbrain/Menu-Wrench#25]
Hi,

In may configuration (see below), the menu assignement tree layout ('Only on the pages selected' and 'On all pages except those selected' options) is broken.

Joomla! 3.4.4, PHP 5.5.26, MySQLi 5.5.42

Best regards
![capture d ecran 2015-09-23 a 17 40 32](https://cloud.githubusercontent.com/assets/10088957/10050089/d742d6ba-621a-11e5-9e38-1c1a09e60e6d.png)

**Comment by Delemo** [comment]
Menu Wrench module is not involved. Same problem in standard Joomla! menu module.
The tree layout was broken because I've left unpublished child links without their parent, in one of my menu.

Thank you

**Comment by betweenbrain** [comment]
Thanks for the update, I do appreciate it.

**Comment by betweenbrain** [comment]
By the way, for future knowledge, most modules are not responsible for the rendering of parameters like these. Joomla core does that on behalf of the module.

**Comment by Delemo** [comment]
Hi Matt,

I should do better testing before posting.
But it was the first time I get this issue, while I'm using Joomla! for a while now.

Best regards

**Comment by betweenbrain** [comment]
It's no problem at all. Happy Joomlaing!

**Comment by buluma** [comment]
Still having this issue despite all menus being in order. any alternate solution to this?
