### ISSUE TITLE
Error: Warning: in_array() expects parameter 2 to be array, null given

### ISSUE THREAD

**Issue by 01Kuzma** [betweenbrain/Menu-Wrench#27]
Hi!
Can't figure out why this error is showing up.
All pages are working fine except one where this errors appears:
http://www.komunikacija.ru/component/chronoforms5/?chronoform=Anketa-v5
Check the footer

Menu Wrench version: 1.1.2
Joomla: 3.4.7

**Comment by betweenbrain** [comment]
Hello,

I am now able to access your site, as it was down before.

Does this issue only occur on pages where Chromo Forms is being used? Are you using the lastest version of the module and Joomla?

**Comment by 01Kuzma** [comment]
Hi!
Yes, I use the latest Chronoforms & Joomla.
As I observed this bug occurs:
1). On this page which uses such link
2).  On all forms opened from Forms Manager -> View Form

Some kind of conflict between Chronoforms & Menu Wrench?

**Comment by betweenbrain** [comment]
Yes, I suspect that this is some sort of conflict with Chronoforms. As the module works fine with core Joomla, I'd suspect Chronoforms might cause conflicts with other extensions.

**Comment by 01Kuzma** [comment]
So what's the better solution?
Send this link to a ChronoForms developers?

**Comment by betweenbrain** [comment]
Technically, it is only a warning and doesn't seem to be causing a functional issue. As you shouldn't have PHP displaying errors in production, simply turning off display errors will resolve this. You will need to contact your hosting company on how to do this.

**Comment by 01Kuzma** [comment]
Hm..., it's set to "simple" in Joomla  in order to have a possibility to keep an eye on errors which could occur . So you suggest just turn if off?

**Comment by betweenbrain** [comment]
Yes, I would not advise enabling any error reporting on a production website as sensitive information could potentially be exposed. I would only turn this on for locally hosted or development sites that are not publicly accessible.

Hope that helps.

**Comment by 01Kuzma** [comment]
Ok, thank you!

**Comment by betweenbrain** [comment]
You're welcome!
