### ISSUE TITLE
Problems after switching to PHP 7.3

### ISSUE THREAD

**Issue by kallehk** [betweenbrain/Menu-Wrench#32]
After switching from PHP 7.2 to PHP 7.3 all menus are gone in front end. Nothing else has changed since the site were transferred from one server to another.

**Comment by betweenbrain** [comment]
Hello,

As you can see, this extension has not had any activity since Sep 19, 2014, and it is no longer being actively supported. I'm surprised that a minor change in PHP would have caused an issue, I would be sure that they are both configured the same.
